### ISSUE TITLE
Patches Script

### ISSUE THREAD

**Issue by StripedMonkey** [Linux74656/SpaceEngineersLinuxPatches#1]
So obviously the patcher needs a little bit of work, @Onyx47 had a bit of a similar idea to me in a few places, specifically how we find the patches and SE needs a bit of work. My *personal* idea was just to check if $HOME/.local/.../SpaceEngineers existed, else ask for user input. Pretty sure Steam follows XDG standards, so $XDG_DATA_HOME would also be possible. Seems the easiest and doesn't require regex stuffs, but you *can* have custom installation directories soooooo...

Other than that I suggest we stick to a style guide, as the current script is a bit of a mishmash (particularly with including a names, `break` at the end of ifs) of different things. So far I've only added my personal interpretation of the automatic SE detection but I kinda wanted to confirm with whoever else wants to contribute before we step over each other's toes and such.

**Comment by Linux74656** [comment]
I am not to familiar with the intricacies of github. I know there is someway i can merge code changes that other suggest... I will look up a video tutorial on how this all works.

My experience is very lacking in python. It is a miracle that the monstrosity I cobbled together actually functions.
I'll gladly take any help i can get on this! Thank you all in advance!

**Comment by Onyx47** [comment]
The rationale for my approach was that every library folder contains `steamdata` and `.acf` files for each application installed in that library folder:

```
onyx@SHODAN:~$ ls .local/share/Steam/steamapps/*244850*
.local/share/Steam/steamapps/appmanifest_244850.acf
onyx@SHODAN:~$ ls Games/Steam/
steamapps
onyx@SHODAN:~$ ls Games/Steam/steamapps/
appmanifest_200900.acf  common  downloading  shadercache  temp
```

This is a test case on my machine, where I added `~/Games/Steam` as a library folder.

I agree that me getting the install folder might've been a bit too paranoid, since that gets autonamed by Steam. Note that just detecting the `.acf` file is the same as checking for the folder, they seem to always be paired up in each library folder. The reason I messed with the file at all is that I wanted to use it to get the game build later on, so I'd just break out the parsing into a separate function later, this bit was more of an experiment on figuring out how Steam handles this.

Just checking for the directory should be fine, honestly, but if we want to avoid generating new checksums all the time (mind you, we could, if we upload patches to a separate server we could also just have a list of checksums there that could be automatically generated by the script building the patch), we will still need the `.acf` file.

**Comment by Linux74656** [comment]
@StripedMonkey 
Auto-detecting the install location is a good idea. It leave less room for user error. If the game is not in the default directory, Is there some way we can list all of the Steam Library folders a user has, then scan them for the .acf?

@Onyx47 
I agree, for simplicity sake we should focus on just using the build numbers pulled from the .acf file.

**Comment by StripedMonkey** [comment]
In the interests of making this a little bit easier to deal with I'm going to suggest breaking out all of the metadata (Checksums, files we're patching, etc.) into a json config like so:

```json
{
    "Versions": {
        "x.x.x.x": {
            "Sandbox.Game.dll" : "checksum",
            "VRage.Scripting.dll" : ""
        },
        "x.x.x.y": {
            ...
        }
    }
}
```
That way all we have to do is iterate through all the files for each version check if they match. If not then patch/update, allowing for
1. it to not need a script update every time a new update happens
2. we can patch as many/little as needed per version.

@Linux74656 As far as can find (was looking for that, all I'm finding is stuff on updating your library inside steam) no. I'm not sure what the best way to determine it either is, without being "invasive".

**Comment by Linux74656** [comment]
@Onyx47 It may be advantageous in preventing lots of user error, to have the script pull @StripedMonkey suggested json config file and compare checksums before applying the patches. This would ensure that they are not applying the patches on top of one another if they do not know what they are doing. I would not mind maintaining a separate file of checksums on this github repo. Assuming i do not miscompile the patches and release them again :sweat_smile: I would not need to do much other than add new entries when the game updates.
We can however, use the buildnumber pulled from the .acf file to simplify the patch naming and downloading process, as well as a stop gap the ensure their is a version available for the users current install before downloading any patches.

**Comment by StripedMonkey** [comment]
https://github.com/StripedMonkey/SpaceEngineersLinuxPatches/blob/master/MonkeyPatcher.py
I'll work on versioning and such later but I made a separate file until got your opinion on it. Overall I think it's a little simpler, and depends only on the files & hashes in a single location. I've not implemented any way to determine the version yet/Grab updates, as that would likely be a net thing and I'd like to make everything more modular before then.

**Comment by Linux74656** [comment]
Wow, I lost track of time. I must admit it is nice to program again... Anyway I added a new script that I think will work. I'll do some more work on it in the morning if needed. I'll happily take any suggestions anyone has on improving the code.

**Comment by StripedMonkey** [comment]
Well, I managed to get the buildID with this regular expression: `(?<="buildid"(\t){2}").*(?=")`
While it's not "super" readable I think it's a pretty simple solution, and is obviously the best solution because regex :P

Right now my fork/MonkeyPatches.py *should* be feature-par with the additional ability to add new patches by making tarfile with the buildid + .tar.gz, inside being the patches with the format filename.patch and adding the build along with the files that need to be added to the patch.

**Comment by StripedMonkey** [comment]
https://github.com/Linux74656/SpaceEngineersLinuxPatches/blob/a298195385371deb6b79ab5c15d0b56e24eb96e9/autopatcherExTest.py#L47-L64
In particular this bit needs some refactoring. The point of `with open(...` is to eliminate the need to x.close() a file and keep the "file" operations to a minimum.

If code review is gonna be a thing I might suggest we use PRs, as they actually have the ability to annotate code via comments.

**Comment by Onyx47** [comment]
PRs are definitely something I approve of.

As for that regex @StripedMonkey, what's the problem with just using something simpler like `"buildid"\s+"(\S+)"` (possibly making the `+` in the capture group explicitly non-greedy, though it seems that this works fine in Python's regex engine)? I don't think they use spaces in those, so it should be good enough and is easier to read. Am I missing an edge case here?

**Comment by StripedMonkey** [comment]
@Onyx47 that regex captures `"buildid"		"4246126"` the regex I mentioned only captures `426126` You don't have to do any post-processing on the string with this method.

**Comment by Onyx47** [comment]
@StripedMonkey that's why `(\S+)` is in parentheses, it's a capture group. Try this code:

```
import re

testString = '"buildid"    "123456"'
result = re.findall(r'\"buildid\"\s+\"(\S+)\"', testString)
print(result)
```

;)

**Comment by StripedMonkey** [comment]
Based on my testing with `re.search()` the result had been `"buildid"  "42...", same with an online regex tester. Testing that way works /shrug. At any rate it's also worth noting you can make *that* one a little cleaner since you don't need to escape the " inside single quotes.

**Comment by Linux74656** [comment]
I updated the autopatcher.py with the experimental script I wrote. I tried it on a computer that did not have space engineers in the default directory and it prompted me to insert the directory. Once i did i ran fine. It also can detect if bsdiff is installed and tell the user if it is not.

My solution to get the build number was to read each line of the acf file until it got the string buildid, then remove buildid and all quotes and  then strip spaces, leaving the only the build number. All of this assumes that the acf file has a buildid and that it follows a similar layout.

**Comment by StripedMonkey** [comment]
So my biggest problem lies in applying the patches. The current system isn't very modular, and requires adding new code for every file that's patched, and if the number of patches grows/shrinks the current system cannot handle that, which is why I've been pushing for the json file to begin with. For Instance the current `Vrage.Scripting.dll` could easily be no longer needed a few updates from now, or  `Vrage.Render.dll` may require a patch tomorrow.

**Comment by StripedMonkey** [comment]
@Linux74656 What are you using the checksum.json for exactly? I've been adapting my code to work with what you've been using and noticed that the checksums for the patches don't match the patched files. Is it just because you've updated it?

**Comment by Linux74656** [comment]
EDIT: I did not read your comment correctly before posting. Sorry.

checksum.json is used to ensure the user has unpatches dlls that match the checksums for the current build. This prevents the user from reapply the patch to an already patched game.

**Comment by Linux74656** [comment]
We seem to have found a better solution to actually fix dotnet. So this script is essentially useless. All mono related fixes have been moved to a sub directory in the repo.
Thank you for all of your help and Happy Space Engineering!
