### ISSUE TITLE
ProtonTricks anyone?

### ISSUE THREAD

**Issue by gallomimia** [Linux74656/SpaceEngineersLinuxPatches#12]
Is any of this possible to do with proton tricks, as opposed to wine tricks? This tool is largely the same afaik, but takes care of the prefix for you, by consulting with steam for the library/game location.

**Comment by Linux74656** [comment]
I forgot protontricks was a thing. It will add a layer of complexity for the user in having to install protontricks if it is not installed already. I added some information in the guide if people already have it installed or wish to install it... but winetricks seems like simplest way (most people can figure out where there steamapps folder containing their game install is) so i'll leave it as the main method, and the method the autopatcher script uses.
