### ISSUE TITLE
vcrun2015 is implied by dotnet472?

### ISSUE THREAD

**Issue by cpw** [Linux74656/SpaceEngineersLinuxPatches#13]
When I followed this setup (using protontricks the other day) - vcrun2015 seemed to be installed as part of dotnet472 so it seems like it might be redundant?
I have _not_ installed vcrun2015 and the game is running flawlessly (modulo looping audio problem)

**Comment by Linux74656** [comment]
I am fairly certain dotnet472 does not install vcruntimes by default... However Steam will install(try to) when you first launch the game with a new prefix. For me, at least, most of the time it installs without issue, but there have been some instances where I get random game crashes or failures to load until I manually installed the visual c++ runtimes. There is no harm in it being reinstalled through winetricks during prefix creation. Having it in the list of things to install is just a precaution to ensure that it is installed in everyone's prefix properly.
