### ISSUE TITLE
[Question] How are things looking for dedicated server ?

### ISSUE THREAD

**Issue by joachimurbain** [Linux74656/SpaceEngineersLinuxPatches#15]
**First, congrats for getting this to work on linux !**

Does this mean, we are close to getting dedicated linux server for SE ?
And if so, how would one get to it ?

Cheers !

**Comment by Linux74656** [comment]
I am not sure how the DS is coming along, but the last i heard it was being discussed on the Linux thread of the SE discord here: https://discordapp.com/invite/keenswh

**Comment by Lazalatin** [comment]
As @Torkiwi found my repository, I might point others from here to it.

Please, if you like, try out (and maybe star) my repository [Lazalatin/space-engineers-dedicated-ubuntu-docker-server](https://github.com/Lazalatin/space-engineers-dedicated-ubuntu-docker-server)

If we put efforts in it together, we might create an easy-to-use and frustration-free, linux-ready Space Engineers dedicated server 👍
