### ISSUE TITLE
It works! And then it doesn't.

### ISSUE THREAD

**Issue by gallomimia** [Linux74656/SpaceEngineersLinuxPatches#17]
I had quite a lot of success with the process described here. The script worked well. Performance was amazing, even on ultra with heavily modded servers. The CPU doesn't churn, the fan doesn't sound like a jet engine anymore, and almost no jitter. But it crashed after about a minute of play. Some better luck on a less modded server with a friend, but the something strange happened. Friend pasted in some kind of station, and then once I was in view of it, things fell apart. The game crashed, and now refuses to load even an empty world without displaying the telltale graphics driver crashed dialog.

I've tried a great many things to attempt to fix this. I deleted the wine prefix and compat data folder. I reran the script. I did a game files integrity check. Nothing seems to allow the game engine to run beyond the startup menu.

Any suggestions are welcome.

For reference I run ubuntu 19.04 with nVidia drivers 430.50 and this is running under proton 4.11-7

**Comment by Linux74656** [comment]
I had this issue twice before. I thought it was a random occurrence, since it has rarely happened. The only way i was able to get around it was to load and use an older save file. If your game is set to autosave it should make backups of the save files. You can find them in prefix save directory for space engineers. (...pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/Saves/VERY LONG STRING OF NUMBERS/WORLDNAME/Backup/)
Worst case scenario is you lose 5 minutes or so of progress. Although I have not seen this issue very often, hopefully after you restore the save from the old backups you will not encounter this issue to often in the future.

**Comment by gallomimia** [comment]
I'm not loading any save file; I'm trying to start a new game or join a different server. Still the crash before any game world displays.

**Comment by Linux74656** [comment]
Try deleting and recreating your prefix. It may also help to verify the integrity of your game files as well.

**Comment by gallomimia** [comment]
I did that already, to no avail. I verified first, and the only two files changed were the ones changed by your script. Now I've deleted the game itself. Not sure if I want to bother reinstalling. There are settings files I should also nuke probably.

**Comment by gallomimia** [comment]
Went thru and nuked as many settings as I could. The launch options remained, but everything else was fresh install. Reapplied the script and rundll32 disable. Everything working fine. Wish I knew what it was that needed repair.

**Comment by Linux74656** [comment]
It may have been something to do with the shader caches. That is what I suspected and was trying to recreate over the past few days, but i have been unable to find any outside of the space engineers prefix directory.

**Comment by Maltahl** [comment]
I can only get it to run via my terminal which results in not being online on steam so the game wont get past any point of starting or loading a new game. 
I followed the manual way of getting Space Engineers running via this page https://github.com/Linux74656/SpaceEngineersLinuxPatches this was due to the script not wanting to run properly on my machine due to a syntax error in it when trying to run it.

@Linux74656 got any good ideas or should i try and make a Lutris runner and do the manually editing of SpaceEngineers.exe.config afterwards ?

**Comment by Linux74656** [comment]
What happens when you try to run the game from steam? Can you add PROTON_LOG=1 %command% to the steam launch options then run the game from steam. Then drop the steam-244850.log file (located in your home directory) here.

**Comment by Maltahl** [comment]
> What happens when you try to run the game from steam? Can you add PROTON_LOG=1 %command% to the steam launch options then run the game from steam. Then drop the steam-244850.log file (located in your home directory) here.

The game launches and run until i choose a mission or join a server and then it freezes.

Log file is 38 MB so i am unable to put it directly in Github so i put it via we-transfer https://we.tl/t-9rCsm92U52

**Comment by Linux74656** [comment]
The posted log does not seem to show a direct issue.
Try posting your space engineers logs from your prefix. they can found in the ..../224850/pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/ there should be two logs SpaceEngineers.log and VRageRenderer-DirectX11.log

**Comment by Maltahl** [comment]
No logs in SteamLibrary/steamapps/compatdata/244850/pfx/drive_c/users/steamuser cause there is no Space Engineer folder, only a Microsoft folder.

**Comment by Maltahl** [comment]
nvm i found the logs here they are:
[SpaceEngineers.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4176908/SpaceEngineers.log)
[VRageRender-DirectX11.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4176909/VRageRender-DirectX11.log)

**Comment by Linux74656** [comment]
Evidently I had the same problem as you do now. I noticed you are using a 5700/5700xt, which happens to be the same card i am using. So i tried starting the game on an RX 580 and it started fine.
So my conclusion is, the newer 5700 series cards are somehow not fully supported yet, for drivers and such.

I was able to get the game to start normally with the 5700xt by(oddly enough) setting all the game settings to minimum(Preset low). Give that a try if it works try setting the graphics settings higher one by one until it crashes.

EDIT: It appears that the voxel quality is the culprit. Make sure it is set to low... as for everything else I set it to high(or enabled it if applicable), and seem to have no issues.

**Comment by Maltahl** [comment]
@Linux74656 sorry for getting back much later. It worked by reducing Voxel Quality to low but it crashed ( normal game crash) after the game tried to add multiple GPS coordinates at the same time ( lost colony ) but none the less it works :D 

Thank you so much! you rule!

**Comment by dzbyr** [comment]
Thank you so much!
I can able run with proton latest stable 5-0-5. Could you add guide page this information cause I tried many of them.

**Comment by Linux74656** [comment]
I am glad it works now. I will close this issue.
