### ISSUE TITLE
Still won't work after patching

### ISSUE THREAD

**Issue by IanTrudel** [Linux74656/SpaceEngineersLinuxPatches#18]
Steam running on a custom CentOS workstation. I followed the instructions and ran the script, seems to do what it is supposed to do. Ran and then nothing. Verified integrity, tried again. Deleted prefix, reinstalled patches, tried again. Not a thing.

> NVIDIA-SMI 435.17       Driver Version: 435.17       CUDA Version: 10.1

[steam-244850.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/3877463/steam-244850.log)

**Comment by Linux74656** [comment]
I am not really great at reading the logs but it appears that mscoree.dll is not being found in your prefix install. Try using winetricks to force install dotnet48 over-top of your existing prefix and see if that fixes it.
You can do this by changing the prefix location to the actual pfx folder location(the default is /home/YOURUSERNAME/local/share/Steam/steamapps/compatdata/244850/pfx/) in the command below.
`WINEPREFIX="/YOURPREFIXFOLDERLOCATION/." winetricks --force -q dotnet48`

**Comment by IanTrudel** [comment]
Thank you for taking the time. It somehow did help.

Here's what I did that worked:

* Let Steam create the prefix by clicking on the play button.
* `protontricks 244850 --force -q dotnet48`
* `protontricks 244850 --force -q vcrun2017 faudio d3dcompiler_47`
