### ISSUE TITLE
Game fails to launch

### ISSUE THREAD

**Issue by owlshrimp** [Linux74656/SpaceEngineersLinuxPatches#20]
Hi,

Running Ubuntu 18.04.1 (Linux 5.0.0-37-generic, 64 bit). Started with a fresh download of space engineers.

I ran the script provided here to completion. I have tried with winetricks 20191224-next as well as the default Ubuntu winetricks package from 2018. The 20191224-next version fared much better, as the 2018 version only complains about bad command line arguments and doesn't do anything. (though 20191224-next did appear to have some trouble and Ubuntu emitted at least one popup notification of wine crashing during the procedure)

I did get the popup described in the issues once, clicked no. Regardless, every time I try to launch the game it tries to start but nothing appears. The button in steam just eventually goes back to "play" from "cancel" a few seconds after the "preparing to launch window" disappears. I believe I got similar results after having not applied any fixes to the steam install at all.

Thanks,
    -Matt

**Comment by Linux74656** [comment]
Could you post the steam-24450.log file please?
You can get it by adding `PROTON_LOG=1 %command%` to the space engineers launch options in steam. The log should be in your home directory.

And if they exist post your space engineers logs from your prefix. they can found in the `..../pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/` and their should be two logs `SpaceEngineers.log` and `VRageRenderer-DirectX11.log`

**Comment by owlshrimp** [comment]
steam-24450.log: https://pastebin.com/sGpM5BZz

..../pfx/drive_c/users/steamuser/Application Data/ has no "space engineers" folder, only "Microsoft"

If you want I could attempt to recapture the output from prefix generation.

**Comment by Linux74656** [comment]
You log indicates that mscoree.dll could not be found. That means dotnet failed to install. Try manually installing dotnet into your prefix.
Make sure you replace the prefix path with the one you have for space engineers.
`WINEPREFIX=/PATH/TO/YOUR/pfx winetricks --force -q dotnet48`

**Comment by owlshrimp** [comment]
Retrying with no changes: https://pastebin.com/afpNX6F1
Noticed it complained about winbind, so I installed that and retried: https://pastebin.com/HarJUdwb

No change to game launching.
Latest log: https://pastebin.com/BaRvpfNJ

Thanks,
    -Matt

**Comment by Linux74656** [comment]
Alright... your dotnet installer is failing. It also says you are using an older version of wine... you should probably update to the latest for best results. See here for more details: https://wiki.winehq.org/Ubuntu
After that:
Delete your prefix, and recreate it one at a time with, 
`WINEPREFIX=/steam_partition/steam_folder/steamapps/compatdata/244850/pfx winetricks --force -q vcrun2015`
`WINEPREFIX=/steam_partition/steam_folder/steamapps/compatdata/244850/pfx winetricks --force -q dotnet472`
`WINEPREFIX=/steam_partition/steam_folder/steamapps/compatdata/244850/pfx winetricks --force -q xact`
`WINEPREFIX=/steam_partition/steam_folder/steamapps/compatdata/244850/pfx winetricks --force -q d3dcompiler_47`

**Comment by owlshrimp** [comment]
I tried following those instructions, but was met with a chain of unmet dependencies. I think I'm going to try updating from ubuntu mate 18.04 to 19.10 before continuing, instead of resorting to (more) nasty hackery.

Will report back.

**Comment by BeauBouchard** [comment]
> chain of unmet dependencies

When i tried to do the same thing, I did
https://askubuntu.com/questions/1205550/cant-install-wine-on-ubuntu-actually-lubuntu-18-04/1205624

to make sure i had the latest wine / everything
Then updated winetricks, then protontricks

**Comment by owlshrimp** [comment]
I had the same difficulties described, with regard to that missing package.

One of the suggestions there is to install the previous (but still much newer) versions of wine.
I gave that a shot and it failed again, particularly on the dotnet install.

Will give SUSE's package a try.

**Comment by owlshrimp** [comment]
Using wine-5.0 and winetricks 20191224-next still fails the install procedure for dotnet: https://pastebin.com/mc8Bdyn7

**Comment by owlshrimp** [comment]
@BeauBouchard What distro/distro version are you using?

**Comment by Linux74656** [comment]
It fails at dotnet461.
Try forcing dotnet48 instead of dotnet472, and see if you get better results.
You may want to create a fresh prefix for this as well.

**Comment by owlshrimp** [comment]
I erased the files for space engineers, re-downloaded it (though I didn't launch it) and re-ran the patcher script, having an up-to-date copy of wine and winetweaks. Upon first time startup the game installed directx.

Now when I try to launch the game it gets further, showing the splash screen each time before exiting.

The full output from the script and the latest log file is here: https://gist.github.com/Matthew-Bradley/e0cb710fae0ecf432c73bd27293ff556

Thanks for the help thus far,
    -Matthew Bradley

P.S. the only mention of the word "error" I could find that stood out was:
20215.339:000a:000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
The proton log seems to just end abruptly.

**Comment by owlshrimp** [comment]
Re-running the patcher script doesn't change the behaviour.

**Comment by Linux74656** [comment]
Are there any logs in the folder ..../pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/
Specifically SpaceEngineers.log and VRageRenderer-DirectX11.log

**Comment by owlshrimp** [comment]
As it turns out, yes. There is now such a SpaceEngineers folder!

Logs: https://gist.github.com/Matthew-Bradley/46a737511a35a3e041831e422a1f982a

Edit: currently using the closed-source nvidia driver, btw, just avoid complications there

**Comment by Linux74656** [comment]
Can you provide your graphics card make/model. Your logs say 8800 GTS. But the logs have been known to commonly show the wrong graphics card.

**Comment by owlshrimp** [comment]
The card is indeed a GeForce 8800 GT: https://www.newegg.ca/nvidia-geforce-8800-gt-cp187-gpu/p/1B4-00GA-00044

Currently running nividia proprietary driver "version 340.107 from nivdia-340"

The machine has a pair of Xeon 5150 dual-core CPUs (haven't yet swapped in my 5160s) and 32GB of ram.

**Comment by Linux74656** [comment]
Well... I have some rather unfortunate news.
According to Wikipedia (Tesla Microarchetecture / GeForce8 series) https://en.wikipedia.org/wiki/Vulkan_(API)#Compatibility It appears that the Nvidia 8800 GT does not have vulkan support.
You could try adding `PROTON_USE_WINED3D=1 %command%` to you steam launch options. That will force the game to launch using directx11.

**EDIT:** Sorry... I just checked and it seems that the card does not have DirectX11 support either. Space Engineers requires DirectX11 to run at all(unless using DXVK/Vulkan, which the card does not seem to support anyway).
It is unlikely that PROTON_USE_WINED3D=1 %command% will work either.
I am not familiar with anyway to get around this other than using a card that supports vulkan or at least directx11.

**Comment by owlshrimp** [comment]
Gave that a shot and now the game produces a window labelled "Error" after the splash screen, though the window itself is flat tan-coloured with no text.

It got a little further, but it seems it can't find an implementation of directx11.
logs: https://gist.github.com/Matthew-Bradley/eb67a19e6fa9f6e1cbe06497d6e9ee79

The only thing I can think of would be to try switching to the nouveau drivers, which should be among the more mature ones (considering the age of the card) and may bring more up to date interfaces than the proprietary nvidia ones.

I'll report my findings as soon as I get a change to try it.

EDIT: This is somewhat encouraging. It turns out that it may not matter if the card supports directx11 (aside from performance), since directx is exclusively windows-only and wined3d translates directx1-11 to openGL:
https://steamcommunity.com/app/221410/discussions/8/1629664607001626033/
Now if only I could get that to work right. This thing runs Mirror's Edge (directx 10?) after all.

**Comment by Linux74656** [comment]
It seems Space Engineers is still detecting the card as not having DirectX11 capabilities, and refusing to attempt loading past that point.
As for the cards opengl support... you may be able to get it to work, if you can somehow trick SpaceEngineers to thinking that the card is DX11 capable. However i fear if somehow you get it working, performance will not be... playable. The games specs say it requires at minimum of a GTX 750 to run. This means an increase from 112 to 512 cuda cores, and twice as much VRAM.
I think you VRAM is going to be the biggest issue, as wine's OpenGL( as well as DXVK for that matter) already takes more VRAM than native running on windows. Not to mention I was running a GTX960 2GB card a while ago, and the game sometimes struggled to run on that at 720p minimum settings.

I'll admit i do not know of any work around that may help get the game running on your card, you could check around the internet for a solution but unfortunately the age of the card is working against you.

**Comment by owlshrimp** [comment]
What I've learned is that the version of directx-over-opengl emulation that's mainlined in mesa is only directx 9. Mirrors edge is a directx 9 game, but space engineers is directx 11.

I don't think the nvidia drivers are going to get any better, but it's possible that nouveau might implement vulkan in the future. They've recently implemented experimental NIR representation support for NV50 (my card) and above, which is a prerequisite to vulkan support. Vulkan support is something that's on their todo list, though they seem to be currently focused on openCL.
(see: https://fosdem.org/2020/schedule/event/nouveau/attachments/slides/3884/export/events/attachments/nouveau/slides/3884/slides.pdf)

So I'm out of luck without a newer card right now, though it's *theoretically* possible this card might work in the future. At any rate, the remaining problems seem to be with my hardware and my choice of distro, not with steam, space engineers, or this script. ;)

**Comment by Linux74656** [comment]
It is unfortunate the game will not work with your card. I close this issue since there is little this repo/script can do.

Good luck in the future... i hope you can get it too work one way or another.

**Comment by owlshrimp** [comment]
Hi, just wanted to follow up.

I managed to get the game running by dropping back to the unmaintained directx 9 beta on steam. Otherwise it's the same procedure as my most recent install. Had to grab a more up to date version of winetricks and a more up to date version of wine from suse (still out of date on ubuntu I think), then just ran the script and it worked.

The game complains about the lack of directx 11 and says that as a result I can't do planets, but whatever. For my particular card I did turn down the graphics to be quite potato, but your mileage may vary.

I'll update this if I notice any other issues.

**Comment by owlshrimp** [comment]
Game still works, even after removing all of the stuff I had to install to make the script successful.

I didn't fancy having a whole pile of packages from suse and a suse repo installed long-term on my ubuntu system, since that's probably just asking for bugs.
