### ISSUE TITLE
Really bad performance

### ISSUE THREAD

**Issue by jorgegomzar** [Linux74656/SpaceEngineersLinuxPatches#21]
I wasn't sure to reopen the last issue or to create another one, but since it's a completely different problem I am creating a new one.

Got the game to work (thanks BTW), but for as many tweaks I try to apply it's never a comfortable gameplay. It's not "_bad_" as in "_I cannot play like this_", but **almost every second the game lags a bit**.

Using **DXVK_HUD=true** in the launch parameters I was able to take a screenshot of the problem:
![periodic deltas](https://user-images.githubusercontent.com/34076979/73450687-33065680-4366-11ea-8ae4-eadb3054e0db.png)

Those periodic deltas mean that every second there is a drop in the framerate.

As well, when entering the game or going back to the menu this gets worse:
![really bad](https://user-images.githubusercontent.com/34076979/73450697-38fc3780-4366-11ea-9a49-536234c5c5d2.png)

Until date, I've tried:
- Using the **PULSE_LATENCY_MSEC** param, (first I thought it was only affecting sound, so I referred to your solutions)
- Using **-high -heapsize 8388608** params.
- Setting up GPU Mode to **"Prefer maximum performance"**

**Setup information**:
- **Proton 4.15-GE-1**
- Prefix contains: **faudio, vcrun2015, dotnet48, d3dcompiler_47**. Configured as **winxp**.
- Steam parameters: **DXVK_HUD=full DXVK_FILTER_DEVICE_NAME="GeForce" PROTON_LOG=1 PULSE_LATENCY_MSEC=90 %command% -high -heapsize 8388608**

Thanks

**Comment by Linux74656** [comment]
This looks like the dotnet lag that the patch is supposed to fix.
Manually go into you Space Engineers installation directory `..../steamapps/common/SpaceEngineers/Bin64/`
Open the SpaceEngineers.exe.config file and make sure `<gcServer enabled="true" />`
is somewhere below the `<runtime>` tag. If it is missing add it...
You can read more here https://github.com/Linux74656/SpaceEngineersLinuxPatches#step-3

**Comment by jorgegomzar** [comment]
Surely the last time I checked the integrity of the game it was removed...
Thank you, it works perfect now
