### ISSUE TITLE
limited memory error shortly after game starting

### ISSUE THREAD

**Issue by pznqz** [Linux74656/SpaceEngineersLinuxPatches#24]
Started seeing this today, last night no issues at all and have been playing for a 3 weeks or so now without issue. I cannot fathom why this has started happening and am wondering if its just me. Happens whether i load a save, start a new game, join a server or just idle in the main menu.

I thought maybe keen pushed an unannounced patch that caused it, but from the looks of here (https://steamdb.info/app/244850/depots/) that does not appear to be the case.

error prompt along with free memory (even cleared the cache before starting SE as my literal last hail Mary before coming here to write this): https://imgur.com/1MO7wfQ.png
SElog: https://pastebin.com/CRBLpbPC
vrage log: https://pastebin.com/pgF9V4Sn
proton log: [steam-244850.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4209051/steam-244850.log)

cpu: Ryzen 3600
gfx: gtx970
distro Arch
kernel 5.4.15
nvidia drivers 440.44
proton 4.11-12 at first, then tried 5.0-2
the drive with SE and the SE prefix on it has >45GB free space 
(ive seen references to this error prompt from a few years back that mentions that their issue was a lack of drive space in the end so i figured this bears mentioning)

- Verified files and nuked the prefix before reapplying the patch with the auto patch script and got the same results.
- Wiped the install of the game and prefix and tried again, same results.
- Updated kernel and nividia drivers to 5.5.3 and 440.59, wiped and repatched etc, same results.
- Tried the manual process of patching from the readme with and without winxp, so essentially ive tried dotnet472, same results.
- once per prefix, after the first crash, the game prompts you to drop all settings to low with a yes no prompt, either option makes no difference
- Tried removing the gc sever line from se.exe.conig for science, stuttered for a while but ultimately crashed with the same errors. So i don't at all think its a problem with the with this script.

Ive trawled for references to my error from the log and the prompt, only finding references to the prompt along with totally different logs and behaviors. Im just out of ideas for the moment and dont have other linux users to bounce off of so this seemed like an appropriate place to try and see if anyone has been struck by the same affliction.

Ill try some other versions of dot net later, and try and think of network related causes considering where the error starts. Sorry if it is just me and this issue amounts to spam.

**Comment by InflexCZE** [comment]
See https://github.com/Linux74656/SpaceEngineersLinuxPatches/pull/23

**Comment by pznqz** [comment]
im so sorry, its typical that i look everywhere but the keen discord until after i posted this issue

**Comment by pznqz** [comment]
closing, solution is `sudo iptables -A INPUT -s 88.146.207.227 -j DROP`
