### ISSUE TITLE
Patch command failed (I think)

### ISSUE THREAD

**Issue by Zapstars** [Linux74656/SpaceEngineersLinuxPatches#25]
After following the steps to the letter the game still told me .net was out of date. I tried running the command again and noticed that in the readout after the winetricks command, it says "Unknown arg dotnet472" Using dotnet48 returns a similar message. Any help would be greatly appreciated.

**Comment by Linux74656** [comment]
EDIT: Try updating winetricks with:
sudo winetricks --self-update
then run the patch script again.

If it does not work then:
Can you tell me which version of winetricks you are using?
You can find this by typing winetricks --version

**Comment by Zapstars** [comment]
After writing  my comment I tried downloaded winetricks from the internet and installing it that way instead of letting ubuntu do it for me. I'm no longer getting the "unknown arg" but another odd issue is happening now. 

After running the command it gets stuck in a loop spitting out thousands of errors and making my hard drive sound like a diesel engine.

It'll spit this out about a hundred times among other errors before trying it all over again: "PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0"
(Not the only error but is most likely the root)

Also I checked the winetricks version and got "20191224-next - sha256sum: ad7e49675d0a0a1c375e28c43b5c923165fb1950f423d1d8ddbfb48248c99c6d
"

**Comment by Zapstars** [comment]
Just realized I'm using wine 3.0. I'll update to 5.0 and try again.
Edit: Issue still occurs on wine 5.0

**Comment by Linux74656** [comment]
Alright... let's get some logs from the setup process. You need to run the following commands separately: (Note make sure you replace the WINEPREFIX path with the one where Space Engineers is installed at ** Usually located at $HOME/.local/share/Steam/steamapps/compatdata/244850/pfx)

`WINEPREFIX="PATH/TO/SPACEENGINEERS/compatdata/244850/pfx" winetricks --force -q dotnet48 > $HOME/DOTNET.log`

`WINEPREFIX="PATH/TO/SPACEENGINEERS/compatdata/244850/pfx" winetricks --force -q vcrun2015 > $HOME/VCRUN.log`

`WINEPREFIX="PATH/TO/SPACEENGINEERS/compatdata/244850/pfx" winetricks --force -q faudio > $HOME/FAUDIO.log`

**Comment by Zapstars** [comment]
[DOTNET.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4238523/DOTNET.log)
[FAUDIO.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4238524/FAUDIO.log)
[VCRUN.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4238525/VCRUN.log)

My guess is I need a 32 bit install.

**Comment by Linux74656** [comment]
The game requires a 64bit prefix.
However some components need the i386 archetecture enabled to run.
You can enable it with `sudo dpkg --add-architecture i386` the run:
`sudo apt-get update`
`sudo apt-get upgrade`

EDIT:
Does the game start at all now? Does it still show a dotnet error?

**Comment by Zapstars** [comment]
I ran all three commands but it's still complaining about me using a 64-bit prefix. Also, I'm 99% sure I already ran those exact three commands following a guide for installing wine 5.

EDIT: Also the game doesn't start up at all now, even to the .net error window.

**Comment by Linux74656** [comment]
The warning about using a 64bit prefix is normal. It can be ignored for the most applications.
Post the space engineers logs found ..../pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/ and their should be two logs SpaceEngineers.log and VRageRenderer-DirectX11.log

If they do not exist add PROTON_LOG=1 %command% to your steam launch options, then post the steam-244850.log file found in your home directory.

**Comment by Zapstars** [comment]
[SpaceEngineers.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4238621/SpaceEngineers.log)
[VRageRender-DirectX11.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4238623/VRageRender-DirectX11.log)

**Comment by Linux74656** [comment]
First try setting your space engineers wineprefix to winxp, you can do it with:
`WINEPREFIX="PATH/TO/SPACEENGINEERS/compatdata/244850/pfx" winetricks winxp`

If that does not fix it:
Verify the integrity of your game files through steam.
Delete your prefix and recreate it manually with:
WINEPREFIX="PATH/TO/SPACEENGINEERS/compatdata/244850/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47 winxp
If that gets you into the game with a weird stutter, then close the game and run the autopatcher again,
and run this `sudo iptables -A INPUT -s 88.146.207.227 -j DROP` in your terminal(it blocks the space engineers analytics server which has recently been causing issues.)

**Comment by Zapstars** [comment]
Neither patch worked. I'm gonna go ahead and try reinstalling the game again and following the patch from scratch. I'll let you know how it goes.

**Comment by Zapstars** [comment]
Did a complete reinstall of space engineers, edited SpaceEngineers.exe.config, and ran:
`WINEPREFIX="my space engineers/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47 winxp`

Launching the game still brings up the .net error.

**Comment by Linux74656** [comment]
That most likely means it did not install dotnet into the correct prefix...
Where is your game installed? Post your path to SpaceEngineers.exe

**Comment by Zapstars** [comment]
Went back in terminal and copied the exact command I ran:
`WINEPREFIX="/home/dlenhard/.local/share/Steam/steamapps/compatdata/244850/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47 winxp
`

**Comment by Linux74656** [comment]
Is space engineers installed at `"/home/dlenhard/.local/share/Steam/steamapps/common/SpaceEngineers/"` ?
If so that means dotnet48 failed.
Try using your existing prefix and use
`WINEPREFIX="/home/dlenhard/.local/share/Steam/steamapps/compatdata/244850/pfx" winetricks --force -q dotnet472`

**Comment by Zapstars** [comment]
That is where space engineers is installed. 

Also ran the suggested command and it works now, thanks for all the help and sorry for being such a pain.

**Comment by Linux74656** [comment]
It's perfectly alright! I'm glad it works!
