### ISSUE TITLE
SpaceEngineers.exe becomes zombie on exit

### ISSUE THREAD

**Issue by daruuuna** [Linux74656/SpaceEngineersLinuxPatches#26]
Running Arch, upon exiting the game the process has become a zombie and killing the parent transfers the process to PPID 1, leaving some 6GB of RAM unusable until a system reboot is done. Any suggestions?

**Comment by daruuuna** [comment]
Joining the SE discord, apparently this is a universal problem and there's a script to automate a fix, found here: https://github.com/inetknght/linux-profile/blob/master/.bash/kill_space_engineers.bash

I'd suggest adding this to the list of issues in the readme, since it is universal according to folks in discord.

**Comment by Linux74656** [comment]
Updated the readme!

**Comment by VoxelTek** [comment]
i think this can be closed now lol
