### ISSUE TITLE
Wine version hint

### ISSUE THREAD

**Issue by frankbroniewski** [Linux74656/SpaceEngineersLinuxPatches#27]
Hi,

I just ran into an issue running SE while still following the guide. I installed the current Pop!_OS, which is based on Ubuntu 19.10. This comes with Wine version 4.11 and I did not manage to get SE started with this version. I had to install Wine from the WineHQ in order to get SE running. I believe this has to do with wine-mono and wine-gecko which are not in the Ubuntu repo?

Anyway, I think there should be a Wine version hint in the documentation which tells people to use a recent version of Wine. Are there any other required packages that could be mentioned in this context, like DXVK?

I am willing to add a few lines to the doc, if you want me to do that. In any case, thanks for your guide!

**Comment by Linux74656** [comment]
Seems we over looked that. Thanks for pointing it out... I added the info the guide.
