### ISSUE TITLE
Can't install SE fix

### ISSUE THREAD

**Issue by mfreeman72** [Linux74656/SpaceEngineersLinuxPatches#28]
I followed both the directions for the automatic patch and the manual installation. Both are failing. Here's what I get with the manual patch using the latest protontricks release, which doesn't seem to recognize the required dotnet:

~$ protontricks 244850 --force -q dotnet472 vcrun2015 faudio d3dcompiler_47
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924 with wine-5.0-484-g26aac31 and WINEARCH=win64
Unknown arg dotnet472
Usage: /usr/bin/winetricks [options] [command|verb|path-to-verb] ...
Executes given verbs.  Each verb installs an application or changes a setting.

Options:
    --force           Don't check whether packages were already installed
    --gui             Show gui diagnostics even when driven by commandline
    --isolate         Install each app or game in its own bottle (WINEPREFIX)
-k, --keep_isos       Cache isos (allows later installation without disc)
    --no-clean        Don't delete temp directories (useful during debugging)
-q, --unattended      Don't ask any questions, just install automatically
-r, --ddrescue        Retry hard when caching scratched discs
    --showbroken      Even show verbs that are currently broken in wine
-t  --torify          Run downloads under torify, if available
    --verify          Run (automated) GUI tests for verbs, if available
-v, --verbose         Echo all commands as they are executed
-h, --help            Display this message and exit
-V, --version         Display version and exit

Commands:
list                  list categories
list-all              list all categories and their verbs
apps list             list verbs in category 'applications'
benchmarks list       list verbs in category 'benchmarks'
dlls list             list verbs in category 'dlls'
games list            list verbs in category 'games'
settings list         list verbs in category 'settings'
list-cached           list cached-and-ready-to-install verbs
list-download         list verbs which download automatically
list-manual-download  list verbs which download with some help from the user
list-installed        list already-installed verbs
prefix=foobar         select WINEPREFIX=/home/mike/.local/share/wineprefixes/foobar

**Comment by Linux74656** [comment]
> Using winetricks 20180217 - sha256sum: 

This is your issue. WInericks is out of date. I am guessing you installed it from the Ubuntu repository?

You need to install the latest winetricks from the instructions here: https://wiki.winehq.org/Winetricks
Specifically this:

> Installing winetricks
...
> To download and install your own copy of winetricks, you can install it manually like this:
> 
> cd "${HOME}/Downloads"
> wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
> chmod +x winetricks
> sudo cp winetricks /usr/local/bin
> 
> To download and install the (separate) BASH completion script for winetricks:
> 
> cd "${HOME}/Downloads"
> wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks.bash-completion
> sudo cp winetricks.bash-completion /usr/share/bash-completion/completions/winetricks   # Standard location for BASH completion scripts (Arch, Gentoo, OpenSUSE, Fedora, Debian/Ubuntu, Solus)
> 



That should fix your issue.

**Comment by mfreeman72** [comment]
Ok. I have the latest winetricks now. And the patch seems to do a TON more, which I think is a good thing. However, SE is still crashing after displaying the initial splash screen, like it did before any patching was ever attempted. I'm not sure what to do now. Maybe I should try to delete everything and start over from scratch, but with the right winetricks this time?

**Comment by Linux74656** [comment]
Yes do a clean install. Make sure you run Space Engineers from steam(It will try to install components and fail... but that is fine) before you run the script.

**Comment by BloodyIron** [comment]
I've found that the winetricks may not be enough, and for me, I had to use the jar fixer file to fix all the things. Perhaps try that when you get a chance.

**Comment by Linux74656** [comment]
I'll  assume this issue was resolved and close this.
