### ISSUE TITLE
Fails To Make It Past Splash Screen With Python Script

### ISSUE THREAD

**Issue by KitFoxy** [Linux74656/SpaceEngineersLinuxPatches#29]
**Wine is up to date according to pacman.
Winetricks is up to date according to pacman.
Using Manjaro with Gnome.
Have tried different proton versions.**

This is what it prints as it starts after I put in the location.
```
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20191224-next - sha256sum: 3a11b9c07e2d7f5b6c21a5e7ef35c70cbc9344bd9a8e068d74b34793dfee6484 with wine-5.4 and WINEARCH=win64
Executing w_do_call d3dcompiler_47
------------------------------------------------------
```
I got it to run once earlier but then it crashed and refused to pass the splash screen.

---
Above is the initial problem. Adding `PROTON_LOG=1 %command%` has caused a wine dialogue to pop up saying "rundll32.exe - .Net Framework Initialization Error". It then requests I install a specific .Net version, directing me to [here](https://dotnet.microsoft.com/download/dotnet-framework/net48?utm_source=getdotnetframework&utm_medium=referral). The splash screen fails to load. 

**Next Step Taken**
`WINEPREFIX=/PATH/TO/YOUR/pfx winetricks --force -q dotnet48` ran this. Now all steam apps refuse to boot successfully, and space engineers now reaches splash screen but freezes.

Any thoughts? I hope this is comprehensive enough.

**Logs**
[steam-244850.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4398499/steam-244850.log)
[SpaceEngineers.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4398501/SpaceEngineers.log)
[VRageRender-DirectX11.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4398502/VRageRender-DirectX11.log)

**Comment by KitFoxy** [comment]
**Update**
It managed to load into the main menu and then froze up. Mouse was bound to window. Could not open terminal to kill it. Could not kill it with alt + F4. Had to wait for the "not responding" dialogue to come up again in order to kill it.

**Comment by Linux74656** [comment]
If you are having trouble with it freezing at the main menu ensure you have checked this issue: https://github.com/Linux74656/SpaceEngineersLinuxPatches#issue-6

Essentially you need to block the Keen SWH analytics servers. You can do that with:

sudo iptables -A INPUT -s 88.146.207.227 -j DROP

**Comment by KitFoxy** [comment]
Cheers, that seems to have resolved it. It's still hit and miss in loading, but it's close enough for now.
