### ISSUE TITLE
latest patch 1.194 fix

### ISSUE THREAD

**Issue by novaspirit** [Linux74656/SpaceEngineersLinuxPatches#31]
Following your guide and script still presents error on latest SE version 1.194 with frostbit DLC. Found fix to add "PROTON_USE_D9VK=1" in command will boot game as normal on Proton 5.0-5

**Comment by Linux74656** [comment]
Couple of questions:
What errors in particular? Can you post logs from: /steamapps/compatdata/244850/pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/ (Both .log files if available)

Are you using the python script or the Java Jar?

Which graphics card are you using?

**Comment by novaspirit** [comment]
game will not start after pressing play. 

ran the python script

specs:
lenovo 530s
pop os 19.10
nvidia mx150

SpaceEngineers.log
https://pastebin.com/PsH4beuD
VRageRender
https://pastebin.com/suWBD3Cn

**Comment by Linux74656** [comment]
It appears that the game is attempting to use your Intel graphics card rather than your Nvidia one:

Remove  PROTON_USE_D9VK=1 from your steam launch options and then, try running `sudo vulkaninfo` in a terminal. then start the game.
If it works then you will need to run `sudo vulkaninfo` after every systemboot to solve this issue.

**Comment by novaspirit** [comment]
even running sudo vulkaninfo it still attempting to run on iGPU but i was able to get to work on nvidia, thanks for telling me,
when i'm running programs like blender or davinci resolve, it will use iGPU unless i pass this command before it. 
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia
adding that to the space engineers command enabled the NVIDIA GPU to be detected. thanks so much for your help. I completely forgot i need to pass that everytime i run programs that need NV_PRIME

checking nvidia-smi also shows space engineers running.

**Comment by Linux74656** [comment]
Glad you got it working!
