### ISSUE TITLE
Game crashes on splash screen

### ISSUE THREAD

**Issue by 3top1a** [Linux74656/SpaceEngineersLinuxPatches#32]
Every time I try to run SE I get to the small splash screen (NOT fullscreen or the main game) and the game crashes.

The logs show that the 'GameAnalyticsSDK.Net.Logging.GALogger' throws an exception.
[SpaceEngineers_20200511_210600465.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4672171/SpaceEngineers_20200511_210600465.log)
[VRageRender-DirectX11_20200511_210601990.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4672172/VRageRender-DirectX11_20200511_210601990.log)

**Comment by Linux74656** [comment]
Your logs indicate the game is trying to start with mono instead of dotnet.
`2020-05-11 21:06:01.059 - Thread:   1 ->  Environment.Version: Mono 6.13.0 (tarball)`

This means the prefix is missing a dotnet install.
Did you use the Jar patcher here: https://github.com/Linux74656/SpaceEngineersLinuxPatches/blob/master/PatcherGUI.jar ?

**Comment by 3top1a** [comment]
I ran it again and I got a different error
[SpaceEngineers_20200524_13000092.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673337/SpaceEngineers_20200524_13000092.log)
[VRageRender-DirectX11_20200524_130001893.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673338/VRageRender-DirectX11_20200524_130001893.log)

**Comment by Linux74656** [comment]
Try adding `PROTON_USE_WINED3D=1 %command%` to your steam launch options for the game.

**Comment by 3top1a** [comment]
It didn't work.
The VRageRender log changed tho 
[SpaceEngineers_20200524_135612488.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673406/SpaceEngineers_20200524_135612488.log)
[VRageRender-DirectX11_20200524_135614932.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673407/VRageRender-DirectX11_20200524_135614932.log)

**Comment by Linux74656** [comment]
Remove `PROTON_USE_WINED3D=1 %command%`
and add `PROTON_LOG=1 %command%` then run the game again.

Then upload the `steam-244850.log` file located in your home directory.
Also could you upload the log file `PatcherLog.txt` the jar patcher created?

**Comment by 3top1a** [comment]
I don't know why but using `PROTON_LOG=1 %command%` didn't create any log file.
Also, removing `PROTON_USE_WINED3D=1` Has shortened the log file
[SpaceEngineers_20200524_180459812.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673877/SpaceEngineers_20200524_180459812.log)
[VRageRender-DirectX11_20200524_180502316.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673878/VRageRender-DirectX11_20200524_180502316.log)

AND the patcher can't create/modify logs without root (Manjaro/Arch), but running it as root is impossible because of wine
Here is the log with root
[root-PatcherLog.txt](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673883/root-PatcherLog.txt)

**Comment by 3top1a** [comment]
*So I put `command%` in the launch options.
Here are the logs with and without `PROTON_USE_WINED3D`
[no-usewine3d-steam-244850.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673888/no-usewine3d-steam-244850.log)
[with-usewine3d-steam-244850.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4673889/with-usewine3d-steam-244850.log)

**Comment by Linux74656** [comment]
Alright lets do this manually and see if it works:
Remove everything from your steam launch options.
Delete your prefix `/home/not1a/.local/share/Steam/steamapps/compatdata/244850/pfx`
Then run space engineers from steam and let it fail.
Then in your terminal run `WINEPREFIX="/home/not1a/.local/share/Steam/steamapps/compatdata/244850/pfx/" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47`
Then try running the game.

**Comment by 3top1a** [comment]
Didn't work

**Comment by Linux74656** [comment]
Are you using a gtx 560?
What graphics driver version are you using?

**Comment by 3top1a** [comment]
I am using a GTX 560 with the nvidia's driver

**Comment by Linux74656** [comment]
Which version of the drivers?
You can find out by typing nvidia-smi  into your terminal.

**Comment by 3top1a** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.132                Driver Version: 390.132                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 560     Off  | 00000000:01:00.0 N/A |                  N/A |
| 40%   37C    P8    N/A /  N/A |    436MiB /   961MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

**Comment by Linux74656** [comment]
Alright I think I see the problem. 
You need at least 418.49.04(https://github.com/ValveSoftware/Proton/wiki/Requirements).

It appears (according to the nvidia website https://www.nvidia.com/Download/index.aspx?lang=en-us -> https://www.nvidia.com/Download/driverResults.aspx/153832/en-us ) that you are using the latest official Nvidia drivers for your card.

Upgrading past that version may cause extreme instability in your system. I tried a year or so ago, to use a gt 220 with newer drivers than were supported and I could not load into the operating system. I ultimately had to reinstall the operating system to get it working (This was during my early days in linux when I did not know better).

You may be able to get around this by trying to use only directx. With PROTON_USE_WINED3D=1 %command% and installing the directx11 redist from Microsoft's website. however it will likely not be very playable, if at all.

EDIT: 
IIR: someone was able to get a much older version of the game to run using an older card than yours.
Found it. Here see this:
https://github.com/Linux74656/SpaceEngineersLinuxPatches/issues/20#issuecomment-604197372

**Comment by 3top1a** [comment]
Thanks!
