### ISSUE TITLE
It works, (on 2nd try) but GPU is overloaded and poor fps with 1080ti

### ISSUE THREAD

**Issue by jarrard** [Linux74656/SpaceEngineersLinuxPatches#37]
Not sure what the issue is. Am using proton-GE but that should only help things.

GPU overloaded issues messages popup in game and I get around 18fps :(

**Comment by jarrard** [comment]
Restarting game seems to fix it, now I get 80fps.. odd

**Comment by Linux74656** [comment]
I have no idea what would cause that. If it happens again make sure to post any logs you have before restarting. It may be some sort of driver error, or something to do with Glorious Eggrolls Proton version.

**Comment by Linux74656** [comment]
Ill close this as I assume it was a one time fluke.
