### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by Martmists-GH** [Linux74656/SpaceEngineersLinuxPatches#38]
After running the patcher, the game still does not launch.

**Comment by Linux74656** [comment]
Without too much information I have to assume this is some sort of DotNet issue( as it seems to be the issue 90% of the time).
Try manually creating your prefix with the command below. (Make sure to insert the location of your SE prefix)

WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" winetricks --force -q dotnet472 vcrun2015 faudio d3dcompiler_47

**Comment by Martmists-GH** [comment]
That command hangs after a few hours, tried waiting 5 hours until I killed it. The game now does "launch", but the main window never shows up, the only indication I have for it running is steam saying it is.

**Comment by Linux74656** [comment]
This happens commonly as well. Replace dotnet472 with dotnet48 and try again. You will likely have more luck.

WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47

**Comment by databoose** [comment]
> This happens commonly as well. Replace dotnet472 with dotnet48 and try again. You will likely have more luck.
> 
> WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47

This process seems to take a pretty long time but does work surprisingly, i tried with vanilla proton and proton GE (both latest as of this posting) with the .jar patcher only to crash after splash screen, but for some reason this command solves the problem and gets me in-game, i would add this command to the readme for maybe more users to see who are having the same problem, thank you for the help.

**Comment by Martmists-GH** [comment]
Running into some issues;

On a 32-bit wineprefix, the game doesn't launch as it's 64-bit.
On a 64-bit wineprefix, I get the notorious mscorsvw error.

Any ideas?

**Comment by Linux74656** [comment]
@MaryWeeb Try deleting your entire pfx folder, and manually installing all of the components, using dotnet48 instead of dotnet472.

WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47

**Comment by Martmists-GH** [comment]
Same issue. If I wipe and install using 64-bit I get the mscorsvw during winetricks install, if I wipe and install using 32-bit it won't launch.

**Comment by Linux74656** [comment]
Alright, lets gather some information.

If the java autopatcher created a log file please post it here.

If there are any log files in ...pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/: (Something like SpaceEngineers_20200524_140840804.log & VRageRender-DirectX11_20200524_081908219.log) please post them
NOTE: these will only appear if you got SE started after you deleted the prefix.

Which distro are you trying to run the game with(Arch, Debian, Ubuntu, Fedora...):

What version of Wine do you have installed on your computer:

What version of Winetricks are you using:

What version of proton are you using:

**Comment by Martmists-GH** [comment]
> If the java autopatcher created a log file please post it here.

[PatcherLog.txt](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5120555/PatcherLog.txt)

> If there are any log files in ...pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/: (Something like SpaceEngineers_20200524_140840804.log & VRageRender-DirectX11_20200524_081908219.log) please post them

None.

> Which distro are you trying to run the game with(Arch, Debian, Ubuntu, Fedora...):

Arch Linux

> What version of Wine do you have installed on your computer:

Latest from arch repositories (5.15-1)

> What version of Winetricks are you using:

Latest from arch repositories (20200412-1)

> What version of proton are you using:

Manual selection: 5.0-9

---

Note that after running the Patcher GUI again and attempting to launch, I got the following popups:

- "Unable to find a matching runtime for this version" (twice)
- "Unable to find .NET v4.6.1" (I clicked install)

I'm currently waiting to see if anything else pops up or the game decides to launch.

**Comment by Linux74656** [comment]
Ok. Everything is up to date. That is good.
I am familiar with this dotnet461 error it was reported here a long time ago https://github.com/Linux74656/SpaceEngineersLinuxPatches/issues/20.
Usually we get around it by using dotnet48 instead of dotnet472, but seems to not work in this case.

You can try starting the game with mono instead of dotnet. You can do that by uninstalling dotnet from the prefix and installing https://dl.winehq.org/wine/wine-mono/4.9.4/
with the command 
WINEPREFIX="PATH/TO/pfx" wine msiexec -i wine-mono-4.9.4.msi

 It will not let you play the game but if it gets you to a screen like this:
> ![IMG-1101](https://user-images.githubusercontent.com/20823837/66356519-cc7da880-e930-11e9-9d93-ebdd3d33dad8.JPG)

Then that means the dotnet install is the only critical thing failing and we need to focus on how to get past the dotnet461 failure.

**Comment by Martmists-GH** [comment]
I can't reach that screen, the game exits after briefly showing the Space Engineers splash. The dotnet errors seem to be gone though.
[SpaceEngineers_20200825_035740476.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5120972/SpaceEngineers_20200825_035740476.log)
[VRageRender-DirectX11_20200825_035745454.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5120973/VRageRender-DirectX11_20200825_035745454.log)

**Comment by Linux74656** [comment]
It appears the game is detecting dotnet48.
The logs indicate it is trying to use an Intel HD 4000 graphics device, while your processor i7-8750H has an Intel UHD Graphics 630. This could mean your drivers are not installed correctly. However I would guess the game is not trying to use the proper graphics card, especially if your computer is a laptop with multiple gpus.

Does your computer have another graphics device, such as an Nvidia or Amd chip/card?

If not you can try putting this into your steam launch options for space engineers.
`PROTON_USE_WINED3D=1 %command%`

If launch option works the performance will be pretty bad however.

**Comment by Martmists-GH** [comment]
After using optimus-manager to set my desktop graphics card to my nvidia card it seems to work. Closing the issue but will report back with any issues.

**Comment by Martmists-GH** [comment]
So far I've only noticed two things: 

- Video on main menu is missing (not a big deal tbh)
- Alt-tabbing to other windows is no longer working reliably, Space Engineers often takes the inputs meant for other applications. Could be a bug in wine/proton.

**Comment by Martmists-GH** [comment]
Notifications (such as discord) seem to cause the game to freeze/lag until they disappear. The same seems to hold for any other window being focused or "above" space engineers.
