### ISSUE TITLE
Patcher modifies Desktop mimetypes

### ISSUE THREAD

**Issue by Martmists-GH** [Linux74656/SpaceEngineersLinuxPatches#39]
Running the patcher seems to modify mimetypes, resetting all customizations made and opening all links in winebrowser rather than chrome

**Comment by Linux74656** [comment]
I have this issue whenever I create a new wine prefix, or install applicaitons in an existing wine prefix. You can find more about the solution here:
https://askubuntu.com/questions/323437/how-to-prevent-wine-from-adding-file-associations
and more info here:
https://forum.winehq.org/viewtopic.php?f=2&t=18368

**Comment by Linux74656** [comment]
Closing as not a direct patcher, or space engineers specific issue.
