### ISSUE TITLE
Issue 7 fix doesn't work

### ISSUE THREAD

**Issue by T0mstone** [Linux74656/SpaceEngineersLinuxPatches#40]
Creative mode works fine but when I try to spawn in a survival game, once the pod lands, the game crashes and takes the OS with it. Setting the Voxel Quality to "Low" did **not** fix this

- OS: Ubuntu 20.04.1 LTS
- Graphics Card: AMD Radeon 5700 XT

**Comment by T0mstone** [comment]
After turning Grass off (In the Options: Graphics > Grass density, Grass draw distance all the way to the left), it did not crash. I'm not sure though if that was what fixed it.

**Comment by T0mstone** [comment]
Oh, and for the record: I still have voxel quality on "Low"

**Comment by Linux74656** [comment]
It appears that the problem has mutated. It seems like any grass settings above zero cause a complete lock up on my system every time, while voxel settings seem to be hit or miss. I set the voxels to extreme and the game ran fine twice, then locked up my computer another time.
I am going to update the readme fix to simply be: Try setting all graphics options to the lowest possible setting.
