### ISSUE TITLE
PatcherGui gets stuck.

### ISSUE THREAD

**Issue by Astralchroma** [Linux74656/SpaceEngineersLinuxPatches#44]
Keeps looping `00f4:err:ntdll:RtlpWaitForCriticalSection section 7BC60340 "../wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 00f4, blocked by 0024, retrying (60 sec)` or something similer to it.

**Comment by Linux74656** [comment]
It's dotnet frameworks. This happens very commonly. The only known work around is to manually install dotnet48 into the space engineers prefix.
`WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47`

**Comment by Peter-Crawley** [comment]
Ill try running that command.

If this is the case you will probably want to list it on the "Known Issues" stuff.

**Comment by Astralchroma** [comment]
Ok, I tryed running `WINEPREFIX=/home/peter/.steam/steam/steamapps/compatdata/244850/pfx winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47` and its getting stuck at the same point.

**Comment by Astralchroma** [comment]
Ok, I ran a proton tricks command and it works now `protontricks 244850 --force -q dotnet472 vcrun2015 faudio d3dcompiler_47`

**Comment by Linux74656** [comment]
Good to hear you got it working. Dotnet is a real pain in the rear sometimes.
