### ISSUE TITLE
SE crashes on the first frame of the main menu

### ISSUE THREAD

**Issue by 3top1a** [Linux74656/SpaceEngineersLinuxPatches#45]
Since my last posts, I got a new GPU, a 1050Ti.
I wanted to try SE, so I deleted the prefix, ran the game, used the GUI autopatcher, and this happened.

Logs:
[SpaceEngineers_20201115_181613255.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5542612/SpaceEngineers_20201115_181613255.log)
[VRageRender-DirectX11_20201115_181622285.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5542613/VRageRender-DirectX11_20201115_181622285.log)

**Comment by Linux74656** [comment]
You may need to reinstall your nvidia drivers, and make sure they are the newest stable for your card. Proton requires at least 418.49.04 so if you have that or newer, just try reinstalling them.

If that fails try to manually install dotnet48 and vcrun2015 d3d_compiler47 into the already existing prefix, one at a time. Do not delete the prefix before trying this. This worked once for me when I still used an nvidia card.
`WINEPREFIX=/qd/Games/steamapps/compatdata/244850/pfx/ winetricks d3dcompiler_47`
`WINEPREFIX=/qd/Games/steamapps/compatdata/244850/pfx/ winetricks --force -q faudio`
`WINEPREFIX=/qd/Games/steamapps/compatdata/244850/pfx/ winetricks --force -q vcrun2015`
`WINEPREFIX=/qd/Games/steamapps/compatdata/244850/pfx/ winetricks --force -q dotnet48`

**Comment by 3top1a** [comment]
Didn't fix it

**Comment by Linux74656** [comment]
Try replacing your config file with the one on this zip file.
[SpaceEngineers.cfg.zip](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5550939/SpaceEngineers.cfg.zip)
It can be located here: 
`WINEPREFIX=/qd/Games/steamapps/compatdata/244850/pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/`

**Comment by 3top1a** [comment]
Nope, still crashed on the main menu

**Comment by 3top1a** [comment]
Heres my proton log
[steam-244850.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5552186/steam-244850.log)

I did find this:
```
ERROR: Caught a segmentation fault while loading plugin file:
/home/not1a/.local/share/Steam/compatibilitytools.d/Proton-5.9-GE-8-ST/dist/lib64/gstreamer-1.0/libgstnvcodec.so

Please either:
remove it and restart.
run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```

**Comment by 3top1a** [comment]
Switched to 5.9-GE-5-ST and it got past the main menu, will try to play later

**Comment by 3top1a** [comment]
It worked! Thanks!
