### ISSUE TITLE
Workshop items are not listed in game

### ISSUE THREAD

**Issue by Anrock** [Linux74656/SpaceEngineersLinuxPatches#51]
So everything seems to work and I'm trying to start a new game with some mods, but in-game list of mods is empty no matter how many times I've tried hitting refresh button, restarting SE or restarting Steam. Mods do appear as subscribed in Steam workshop.

Is it SE bug or something caused by patcher tampering with SE prefix?

**Comment by Linux74656** [comment]
I have no issue with mods.
Are you sure that you have experimental mode enabled in your game options?

**Comment by Anrock** [comment]
Yes, experimental mode is enabled - I've checked it in game options before hitting "new game" in main menu. Anything else I can check?

**Comment by Linux74656** [comment]
You can try using steam to validate the integrity of game files.
Then you will have to rerun the patcher to reapply the fix, though you should not need to create the prefix again.

**Comment by Anrock** [comment]
Nothing have helped, unfortunately :(

File verification repaired two files, then I've reapplied patches - nope.
Tried deleting the prefix and going from fresh start (starting from steam and waiting for fail then applying patches) - didn't work either.

**Comment by Linux74656** [comment]
Have you tried unsubscribing and then resubscribing to all of the mods on steam?
If not, then you may need to delete the mod folder in your steam directory, Usually here: /home/USERNAME/.steam/steam/steamapps//workshop/content/244850/
and the file appworkshop_244850.acf usually found here:  /home/USERNAME/.steam/steam/steamapps//workshop.
Then try restarting steam and unsubscribing and re subscribing to the mods.

**Comment by Anrock** [comment]
Nope, didn't work. I've also noted that in-game workshop browser doesn't work - everything is empty and spinner spinning forever.
I've also tried to launch SE with PROTON_LOG=1 and there are curious lines in log:

```
35284.091:002c:002d:warn:debugstr:OutputDebugStringA "[S_API] SteamAPI_Init(): Loaded 'C:\\Program Files (x86)\\Steam\\steamclient64.dll' OK.\n"`
...
35284.151:002c:002d:err:steamclient:create_win_interface Don't recognize interface name: SteamUtils010
35284.151:002c:002d:warn:debugstr:OutputDebugStringA "[S_API FAIL] SteamAPI_Init() failed; no appID found.\nEither launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.\n"
```
Could it be the reason why workshop integration isn't working for game?

**Comment by Anrock** [comment]
Tho creating steam_appid.txt with 244850 inside in SE and SE/Bin64 folder didn't help too and the message is still in the log.

**Comment by Linux74656** [comment]
That could be the reason it is not working, but i have no experience with this issue. You may try asking on this issue, https://github.com/ValveSoftware/Proton/issues/1792, as there are far more experienced people there.

**Comment by Anrock** [comment]
Okay, thank you for all the help. I'm closing the issue then.

**Comment by Daedalusspacegames** [comment]
I did some testing and was able to recreate this issue. Best I can tell, the default behaviour of the autopatcher, specifically disabling rundll32, prevents the Steam Integration from loading properly. Running without disabling rundll32 allowed the game to run properly with Workshop and everything.

**Comment by Anrock** [comment]
@Daedalusspacegames gonna try that. Any downsides in disabling rundll32?
