### ISSUE TITLE
Can't install dotnet40 without downgrading proton.

### ISSUE THREAD

**Issue by khaddra** [Linux74656/SpaceEngineersLinuxPatches#52]
Dotnet40 is required to install dotnet48 and dotnet472, but fails to install at proton 6.3-2 and 5.13-6. Installation was successful at proton 4.11-13. I had to upgrade back to proton 6.3-2 to be able to use online features.

I get that you probably can't do much about this, but it would be very helpful to mention it in the known issues section.

I am using gentoo with openRC and kernel 5.4.97-gentoo-x86_64. I have an AMD Ryzen 5 3600.

**Comment by Linux74656** [comment]
Sorry about the long delay ive been really busy as of late. Ill  add this right away.

**Comment by khaddra** [comment]
I haven't tested it myself, but on ProtonDB (https://www.protondb.com/app/244850), most people are saying that they had to downgrade to 5.0, so maybe you should change the recommendation in the readme to that.
