### ISSUE TITLE
Crash after VRage splash in SE v1.198

### ISSUE THREAD

**Issue by ryanwalder** [Linux74656/SpaceEngineersLinuxPatches#53]
Thought I'd link to the known issue with SE v1.198 here to save some folks the pain I've just been through:

https://support.keenswh.com/spaceengineers/pc/topic/v1-198-getgeoinfo-analytics-causes-crash-with-proton

This is not mitigated by blocking the analytics IP with iptables/nf.

Awaiting patch, downgrading to v1.197 works at present.

**Comment by mkaito** [comment]
I'm told this helps, I'm trying to test right now https://github.com/sehrAlterEgo/SE-WinePatches

**Comment by ryanwalder** [comment]
After the patch today (2021-04-29) I can confirm it is working again. I am getting audio buzzing now though which seems to vary in intensity/doesn't happen at random on each launch (sometimes no buzzing, sometimes log buzzing, sometimes quiet buzzing etc...)

**Comment by ryanwalder** [comment]
Ignore that the buzzing was caused by the DKXV hud. This this can safely be closed now.
