### ISSUE TITLE
After updating nvidia drivers to latest 460 or to 470 game crashes very frequently, hard drop to desktop

### ISSUE THREAD

**Issue by stubkan** [Linux74656/SpaceEngineersLinuxPatches#57]
Currently on 470.95, Ubuntu 20.04.  RTX 2060. Have applied all fixes and prior to the update, Space Engineers ran almost flawlessly.  Trying to pinpoint cause of crashing but cant find anything consistent.

VRAGE Render and SpaceEngineers logs seem to cut out without any error messages, just stop during normal logging.

syslog has nothing.

steam logs ends with this

```
trace:loaddll:build_module Loaded L"C:\\windows\\system32\\api-ms-win-appmodel-runtime-l1-1-1.dll" at 000000024DC40000: builtin
fixme:ver:GetCurrentPackageId (000000000032FDB0 0000000000000000): stub
pid 74876 != 74875, skipping destruction (fork without exec?)
```

pid skipping destruction, is apparently how proton/steam closes games normally, so it is force shutting it down for SOME reason?

**Comment by 3top1a** [comment]
How did you fix this? I think I'm having a similar problem but have no clue how to get rid of it.
