### ISSUE TITLE
Prefix Configuration

### ISSUE THREAD

**Issue by StripedMonkey** [Linux74656/SpaceEngineersLinuxPatches#6]
Right now we're leaving prefix installation up to the user, which is likely the source of some problems and confusion. I figure at least documenting it in the form of a script might be ideal. Best-case we use something like Lutris to configure prefixes and automate that. Second best is to just provide a script in the repo (which we can still do), but lutris has documentation [here](https://github.com/lutris/lutris/blob/master/docs/installers.rst) and it's not that difficult to ensure everything's installed properly that way. That would also ensure we have some consistency in setup. Keeping track of the Proton issue page is kinda a mess, considering everyone has their own configs that seem to work for them.

We'll still need to maintain a way to patch the scripts, since (AFAIK anyways) they don't provide a way to patch binary files.

**Comment by Linux74656** [comment]
We had a major break through! It is no longer nessicary to patch the game with mono anymore!

**Comment by StripedMonkey** [comment]
I hit the button before I saw that, but either way I do think it would be worth it to get a lutris script up, since that's the platform most people use for wine stuffs anyways. I'm glad we don't need to use a patch now though.

**Comment by Linux74656** [comment]
Alright. I agree. Does lutris have the ability to modify a specific file without user input?

**Comment by StripedMonkey** [comment]
At least according to the docs it only has the ability to (currently) modify ini and json files, however we could use the command `xsltproc` (which was installed on my machine, I assume as apart of base-devel or something but It's on ubuntu machines as well) to [modify xml configs](https://stackoverflow.com/questions/6873070/how-to-edit-xml-using-bash-script) pretty easily. You can pretty easily add commands to be executed during install, so it's not crazy.

**Comment by Linux74656** [comment]
I think we can close this as this is a proton/linux support page. If someone wants to create a repo for lutris support i will gladly link it in the readme.
