### ISSUE TITLE
No executable found matching command

### ISSUE THREAD

**Issue by Evernow** [Linux74656/SpaceEngineersLinuxPatches#7]
Hello there!

I am terribly sorry if this was answered before, but I tried following the guide and I couldn't figure it out, trying to run this command but get the following

[daniel@daniel-pc ~]$ dotnet WINEPREFIX="/run/media/daniel/O/SteamLibrary/steamapps/compatdata/244850/pfx/" winetricks --force -q dotnet472 vcrun2015 xact
No executable found matching command "dotnet-WINEPREFIX=/run/media/daniel/O/SteamLibrary/steamapps/compatdata/244850/pfx/"

Any help is greatly appreciated!

**Comment by StripedMonkey** [comment]
the command is
`WINEPREFIX="/run/media/daniel/O/SteamLibrary/steamapps/compatdata/244850/pfx/" winetricks --force -q dotnet472 vcrun2015 xact`

not 
`dotnet WINEPREFIX="/run/media/daniel/O/SteamLibrary/steamapps/compatdata/244850/pfx/" winetricks --force -q dotnet472 vcrun2015 xact`

**Comment by Linux74656** [comment]
Sorry about that. I have updated the readme, it was malformed and the command was on the same line as the previous sentence. Just remove dotnet from the front of your command and it should work!

**Comment by Evernow** [comment]
Sorry for not getting back to you, but thank you so much! Been playing the game for the last two weeks and it's been AMAZING! Small issues like sometimes it crashing during loading, alt tabbing making the entire screen go insane and sometimes the skybox and animations are purple, but no issues that aren't fixed by simply alt tabbing in or restarting the game!

Thank you so much everyone!
