### ISSUE TITLE
".NET is out of date" on start

### ISSUE THREAD

**Issue by ilovehans10** [Linux74656/SpaceEngineersLinuxPatches#9]
I followed the steps in the proper order and nothing seemed to be off with any of them. I didn't closely read the output step 2, but I did see that there were some messages that said processes were completing properly. I also did the change of renaming the video so I wouldn't have to worry about it. However when I opened the game it gave me the message "Please update your .NET runtime with this hotfix:\nhttps://support.microsoft.com/kb/3120241\n\nThe game will not run correctly otherwise." and froze. I was able to kill it after a bit and upon relaunch clicking multiple times caused it to close itself however I do not know if it just crashed. I then restarted my computer hoping that this might fix it but the game continued to show this error and sometimes close. Also when it closes it opens [this link](https://support.microsoft.com/en-us/help/3120241/hotfix-rollup-3120241-for-the-net-framework-4-6-and-4-6-1-on-windows) in Firefox. I am inexperienced in wine so I do not know how to use the hotfix. Any help is appreciated.
![IMG-1101](https://user-images.githubusercontent.com/20823837/66356519-cc7da880-e930-11e9-9d93-ebdd3d33dad8.JPG)

**Comment by Linux74656** [comment]
Try deleting your prefix and running this

`WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47`

Make sure you replace INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx with the location of your Space Engineers prefix. If you installed space engineers to your default library folder, it is usually found at /home/YOURUSERNAME/.steam/steam/steamapps/compatdata/244850/pfx/

**Comment by ilovehans10** [comment]
That worked a charm!
I would however recommend clarifying somewhere in the instructions that the prefix is in compatdata/244850/pfx and not common/SpaceEngineers/pfx which is what I had originally tried and had seemed to have worked for me.

**Comment by MemphisCornelius** [comment]
Hey,
I have the same problem, but "WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47" did not work. Is there anything else I could try?

**Comment by Linux74656** [comment]
@MemphisCornelius 
> Hey,
> I have the same problem, but "WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" winetricks --force -q dotnet48 vcrun2015 faudio d3dcompiler_47" did not work. Is there anything else I could try?

This usually means the prefix is not installed to the correct directory. You need to make sure you change ` "WINEPREFIX="INSERT/DIRECTORY/TO/SPACEENGINEERS/pfx" ` to be your space engineers prefix directory. You can try using the script i wrote ![here](https://github.com/Linux74656/SpaceEngineersLinuxPatches) it will try to find your prefix location for you. If it cannot find it, you will need to enter the steamapps folder location of where the game is installed. For example, if you installed the game to an external HDD, the game directory would be somthing like:

/mnt/SSD/Steamfolder/steamapps/common/SpaceEngineers/

 When the script asks you would enter:

/mnt/SSD/Steamfolder/steamapps/. 
NOTE: Make sure you use your actual directory location, above is just an example.

**Comment by MemphisCornelius** [comment]
Yes
this was my problem.

Thanks
